name: Deploy PHP Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via rsync
        # uses: appleboy/ssh-action@v0.1.7
        # env:
        #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/id_rsa
          rsync -av --delete --exclude=".env" --exclude="storage/" -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/pav/stacks/mysite/html/
          rm -f ~/.ssh/id_rsa
